application: reservation-115421
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers: 
- url: /(creater|createreservation)
  script: create.application
  login: required

- url: /view
  script: view.application

- url: /delete
  script: delete.application
  login: required

- url: /edit
  script: edit.application
  login: required


- url: /
  script: landing.application

- url: /(viewyourresource|viewyourreservations)
  script: user.application
  login: required

  


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

